### ISSUE TITLE
Cant make it work on Cuda [windows]

### ISSUE THREAD

**Issue by Rokazas** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#10]
Hi

CPU works, but cuda shows error. I cant figure out how to fix it.
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Thanks

**Comment by ProNoobLi** [comment]
g_loss[ind] = loss.cpu().data 
Adding .cpu() works

**Comment by lavi135246** [comment]
I have fixed it in the latest version. Thanks
