### ISSUE TITLE
Maybe There is a bug in train.py, when flip the image

### ISSUE THREAD

**Issue by zhengtianyu1996** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#11]
Here in the second if, I think the axis should be 2.  axis=0 means flip along the batch dimension

        if np.random.randint(2,size=1)[0] == 1:  # random flip 
            input_patch = np.flip(input_patch, axis=1)
            gt_patch = np.flip(gt_patch, axis=1)
        if np.random.randint(2,size=1)[0] == 1: 
            input_patch = np.flip(input_patch, **axis=0**)
            gt_patch = np.flip(gt_patch, **axis=0**)
        if np.random.randint(2,size=1)[0] == 1:  # random transpose 
            input_patch = np.transpose(input_patch, (0,2,1,3))
            gt_patch = np.transpose(gt_patch, (0,2,1,3))

**Comment by lavi135246** [comment]
You're right. Thanks
It is fixed in the latest version.
