### ISSUE TITLE
about train_sony code

### ISSUE THREAD

**Issue by jingzhang697** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#14]
In the  train_sony  code,how to modify the  batch_size?

**Comment by lavi135246** [comment]
We don't support batch sizes of more than 1 due to the memory issue. I suggest you redesign the flow to meet your requirements. However, I could tell you the easiest way to change batch size is to append multiple patches before you feed into the model.

**Comment by jingzhang697** [comment]
您好，在这个训练代码中，这句[:,yy:yy+ps,xx:xx+ps,:]语句中的四个参数代表的含义我不太理解，希望能够解答一下input_patch = input_images[str(ratio)[0:3]][ind][:,yy:yy+ps,xx:xx+ps,:]




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lavi135246/pytorch-Learning-to-See-in-the-Dark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月23日(星期二) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lavi135246/pytorch-Learning-to-See-in-the-Dark] about train_sony code (#14)





 
We don't support batch sizes of more than 1 due to the memory issue. I suggest you redesign the flow to meet your requirements. However, I could tell you the easiest way to change batch size is to append multiple patches before you feed into the model.
