### ISSUE TITLE
  im = raw.postprocess

### ISSUE THREAD

**Issue by zhangyulee** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#5]
How to understand   im = raw.postprocess(use_camera_wb=True, half_size=False, no_auto_bright=True, output_bps=16)

**Comment by ninetf135246** [comment]
The variable `raw` is a **rawpy.RawPy** class object. The function `postprocess` is one of its function.
For more information you may visit the following links:
https://letmaik.github.io/rawpy/api/rawpy.RawPy.html
https://letmaik.github.io/rawpy/api/rawpy.Params.html#rawpy.Params

Also, you may search with the keywords **_python rawpy postprocess_**.
