### ISSUE TITLE
gt_full = np.expand_dims(np.float32(im/65535.0),axis = 0)

### ISSUE THREAD

**Issue by zhangyulee** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#7]
gt_full = np.expand_dims(np.float32(im/65535.0),axis = 0)，
I think it should be 65532.

**Comment by ninetf135246** [comment]
Can you explain why you think it should be 65532?

**Comment by zhangyulee** [comment]
I don't understand why it is 65535, the final output is not 16bit?   2^16=65532

**Comment by ninetf135246** [comment]
2^16 = 65536 
There is a problem with your calculator.

The range of 8-bit image is from 0x00 to 0xFF (0-255). 
Following the same line, a 16-bit image will be ranged from 0x0000 to 0xFFFF (0-65535).

**Comment by zhangyulee** [comment]
Forgive me for making a low-level mistake, thank you for your patience.
